# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_product_test.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_db_product_test(object):
    def setupUi(self, db_product_test):
        db_product_test.setObjectName("db_product_test")
        db_product_test.resize(634, 418)
        self.centralwidget = QtWidgets.QWidget(db_product_test)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout_fix = QtWidgets.QVBoxLayout()
        self.layout_fix.setObjectName("layout_fix")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_id.sizePolicy().hasHeightForWidth())
        self.label_id.setSizePolicy(sizePolicy)
        self.label_id.setText("")
        self.label_id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_id.setObjectName("label_id")
        self.layout_fix.addWidget(self.label_id)
        self.label_descr = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_descr.sizePolicy().hasHeightForWidth())
        self.label_descr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_descr.setFont(font)
        self.label_descr.setText("")
        self.label_descr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_descr.setObjectName("label_descr")
        self.layout_fix.addWidget(self.label_descr)
        self.label_download = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_download.sizePolicy().hasHeightForWidth())
        self.label_download.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_download.setFont(font)
        self.label_download.setText("")
        self.label_download.setAlignment(QtCore.Qt.AlignCenter)
        self.label_download.setObjectName("label_download")
        self.layout_fix.addWidget(self.label_download)
        self.scroll_area_seq = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_seq.sizePolicy().hasHeightForWidth())
        self.scroll_area_seq.setSizePolicy(sizePolicy)
        self.scroll_area_seq.setMinimumSize(QtCore.QSize(551, 0))
        self.scroll_area_seq.setWidgetResizable(True)
        self.scroll_area_seq.setObjectName("scroll_area_seq")
        self.area_seq = QtWidgets.QWidget()
        self.area_seq.setGeometry(QtCore.QRect(0, 0, 612, 199))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.area_seq.sizePolicy().hasHeightForWidth())
        self.area_seq.setSizePolicy(sizePolicy)
        self.area_seq.setMinimumSize(QtCore.QSize(0, 13))
        self.area_seq.setObjectName("area_seq")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.area_seq)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_seq = QtWidgets.QLabel(self.area_seq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_seq.sizePolicy().hasHeightForWidth())
        self.label_seq.setSizePolicy(sizePolicy)
        self.label_seq.setMinimumSize(QtCore.QSize(565, 0))
        self.label_seq.setTextFormat(QtCore.Qt.RichText)
        self.label_seq.setScaledContents(True)
        self.label_seq.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_seq.setWordWrap(True)
        self.label_seq.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_seq.setObjectName("label_seq")
        self.verticalLayout.addWidget(self.label_seq)
        self.scroll_area_seq.setWidget(self.area_seq)
        self.layout_fix.addWidget(self.scroll_area_seq)
        self.layout_feature = QtWidgets.QHBoxLayout()
        self.layout_feature.setObjectName("layout_feature")
        self.scroll_area_button = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_button.sizePolicy().hasHeightForWidth())
        self.scroll_area_button.setSizePolicy(sizePolicy)
        self.scroll_area_button.setMinimumSize(QtCore.QSize(0, 111))
        self.scroll_area_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_area_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scroll_area_button.setWidgetResizable(True)
        self.scroll_area_button.setObjectName("scroll_area_button")
        self.area_button = QtWidgets.QWidget()
        self.area_button.setGeometry(QtCore.QRect(0, 0, 610, 109))
        self.area_button.setObjectName("area_button")
        self.scroll_area_button.setWidget(self.area_button)
        self.layout_feature.addWidget(self.scroll_area_button)
        self.layout_fix.addLayout(self.layout_feature)
        self.horizontalLayout.addLayout(self.layout_fix)
        db_product_test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(db_product_test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 634, 21))
        self.menubar.setObjectName("menubar")
        self.menu_outils = QtWidgets.QMenu(self.menubar)
        self.menu_outils.setObjectName("menu_outils")
        self.menu_afficher = QtWidgets.QMenu(self.menubar)
        self.menu_afficher.setObjectName("menu_afficher")
        db_product_test.setMenuBar(self.menubar)
        self.action_gen = QtWidgets.QAction(db_product_test)
        self.action_gen.setCheckable(True)
        self.action_gen.setObjectName("action_gen")
        self.action_analyser = QtWidgets.QAction(db_product_test)
        self.action_analyser.setObjectName("action_analyser")
        self.action_ref = QtWidgets.QAction(db_product_test)
        self.action_ref.setCheckable(True)
        self.action_ref.setObjectName("action_ref")
        self.menu_outils.addAction(self.action_analyser)
        self.menu_afficher.addAction(self.action_gen)
        self.menu_afficher.addAction(self.action_ref)
        self.menubar.addAction(self.menu_afficher.menuAction())
        self.menubar.addAction(self.menu_outils.menuAction())

        self.retranslateUi(db_product_test)
        self.action_gen.toggled['bool'].connect(db_product_test.action_gen_toggled)
        self.action_ref.toggled['bool'].connect(db_product_test.action_ref_toggled)
        QtCore.QMetaObject.connectSlotsByName(db_product_test)

    def retranslateUi(self, db_product_test):
        _translate = QtCore.QCoreApplication.translate
        db_product_test.setWindowTitle(_translate("db_product_test", "MainWindow"))
        self.label_seq.setText(_translate("db_product_test", "<html><head/><body><p><br/></p></body></html>"))
        self.menu_outils.setTitle(_translate("db_product_test", "Outils"))
        self.menu_afficher.setTitle(_translate("db_product_test", "Afficher"))
        self.action_gen.setText(_translate("db_product_test", "Généralités"))
        self.action_analyser.setText(_translate("db_product_test", "Analyser la séquences"))
        self.action_ref.setText(_translate("db_product_test", "Références"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    db_product_test = QtWidgets.QMainWindow()
    ui = Ui_db_product_test()
    ui.setupUi(db_product_test)
    db_product_test.show()
    sys.exit(app.exec_())
